name: Docker Build and Release
on: [ push, workflow_dispatch ]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN_2024 }}  # Needed to get PR information, if any
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
        cache: maven
    #### AUFGABE 2: SONAR
    # hier ist der Platz für die Konfiguration der Sonar Analyse
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Sonar analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_2024 }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=peter-H_pet-clinic       
    - name: Compile, build and push
      run: |
        #### AUFGABE 3 COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build
          mvn package
          #docker build --tag peterhertkorn/pet-clinic:latest -f Dockerfile .
          #docker login -u peterhertkorn -p ${{ secrets.DOCKERHUB_TOKEN }}
          #docker image push peterhertkorn/pet-clinic:latest
          docker build --tag ghcr.io/peter-h/pet-clinic:latest -f Dockerfile .
          echo ${{ secrets.GH_TOKEN_2024 }} | docker login ghcr.io -u peter-H --password-stdin
          docker image push ghcr.io/peter-h/pet-clinic:latest
          
